In [ ]:
import numpy as np

Augmented Matrix:

In [ ]:
d= 3                                #dimension dx(d+1).......d=number of rows

line1= np.array([2,3,4,1])
line2= np.array([3,4,2,5])           #system of linear equations 
line3= np.array([7,3,9,7])

augmented_matrix= np.array([line1, line2, line3])
#coefficient_matrix= np.delete(augmented_matrix,d,d-2)
#print(coefficient_matrix)
print(augmented_matrix)  

[[2 3 4 1]
 [3 4 2 5]
 [7 3 9 7]]


Converting Augmented Matrix to Echelon form:

In [ ]:
dummylist1= [augmented_matrix[0]]
dummylist2= [augmented_matrix[0]]

def echelon_form(augmented_matrix):

  for j in range(2,d+1):
    for i in range(2,d+1):
      multiplier_i= augmented_matrix[j-2][j-2]/augmented_matrix[i-1][j-2]
      line_i= augmented_matrix[j-2]- multiplier_i*augmented_matrix[i-1]
      dummylist1.append(line_i) 
    dummylist2.append(line_i)  
    augmented_matrix= np.array(dummylist1) 
  echelon_matrix= np.array(dummylist2)  
  return echelon_matrix

echelon_mat= echelon_form(augmented_matrix)
print(echelon_mat) 

[[ 2.          3.          4.          1.        ]
 [ 0.          2.14285714  1.42857143 -1.        ]
 [ 0.          0.          2.44444444 -2.17777778]]


In [ ]:
echelonform_coefficient_mat= np.delete(echelon_mat,d,d-2)
#print(echelonform_coefficient_mat)
if np.allclose(echelonform_coefficient_mat, np.triu(echelonform_coefficient_mat))== True:
  print('The system of linear equations is consistent and has a unique solution.')
else:
  print('The system of linear equations has either infinite number of solution or no solutions.')  

The system of linear equations is consistent and has a unique solution.


Back Substituition:

In [ ]:
x = np.zeros(d)

x[d-1] = echelon_mat[d-1][d]/echelon_mat[d-1][d-1]
for i in range(d-2,-1,-1):
    x[i] = echelon_mat[i][d]
    for j in range(i+1,d):
        x[i] = x[i] - echelon_mat[i][j]*x[j]
    x[i] = x[i]/echelon_mat[i][i]

print('The solution to the systems of linear equations is:')
print('---'*20)
for i in range(d):
    print('X'+str(i)+'=',x[i])

The solution to the systems of linear equations is:
------------------------------------------------------------
X0= 2.090909090909091
X1= 0.12727272727272726
X2= -0.8909090909090908
